#!/bin/bash

rojo='\033[1;31m'
verde='\033[1;32m'
reset='\033[0m'

echo -e "${verde}██████╗  ██████╗  ██████╗██╗  ██╗███████╗██████╗ ██╗      █████╗ ██████╗ ███████╗"
echo -e "██╔══██╗██╔═══██╗██╔════╝██║ ██╔╝██╔════╝██╔══██╗██║     ██╔══██╗██╔══██╗██╔════╝"
echo -e "██║  ██║██║   ██║██║     █████╔╝ █████╗  ██████╔╝██║     ███████║██████╔╝███████╗"
echo -e "██║  ██║██║   ██║██║     ██╔═██╗ ██╔══╝  ██╔══██╗██║     ██╔══██║██╔══██╗╚════██║"
echo -e "██████╔╝╚██████╔╝╚██████╗██║  ██╗███████╗██║  ██║███████╗██║  ██║██████╔╝███████║"
echo -e "╚═════╝  ╚═════╝  ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═════╝ ╚══════╝"
echo -e "\n"
echo -e " ██████╗██╗     ███████╗ █████╗ ███╗   ██╗                                       "
echo -e "██╔════╝██║     ██╔════╝██╔══██╗████╗  ██║                                       "
echo -e "██║     ██║     █████╗  ███████║██╔██╗ ██║                                       "
echo -e "██║     ██║     ██╔══╝  ██╔══██║██║╚██╗██║                                       "
echo -e "╚██████╗███████╗███████╗██║  ██║██║ ╚████║                                       "
echo -e " ╚═════╝╚══════╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝                                       ${reset}"                           
echo -e "${rojo}Instagram: macim0_${reset}"

sleep 3

clear

echo -e "${verde}Este script se encarga de limpiar los contenedores docker que no han sido borrados del todo (docker ps -a)${reset}"

if [ $(id -u) -ne 0 ]; then
  echo -e "${rojo}Ejecuta este script como root para evitar problemas${reset}"
  exit 1
fi

for i in $(docker ps -a | awk '{print $1}' | sed 's/CONTAINER//g'); do
  echo -e "[+] ${verde}Borrando el contenedor: $i${reset}"
  docker rm "$i" > /dev/null 2>&1

done

read -p "Tambien deseas borrar las imagenes? 's' o 'n': " decision

if [ "$decision" == "s" ]; then
  for i in $(docker images | awk '{print $3}' | sed 's/IMAGE//g'); do
    echo -e "[+] ${verde}Eliminando la imagen con id: $i${reset}"
    docker rmi -f "$i" > /dev/null 2>&1
  done
elif [ "$decision" == "n" ]; then
  echo -e "${verde}Saliendo...${reset}"
  exit 0
else
  echo -e "[-] ${rojo}Opción incorrecta... Saliendo.... ${reset}"
  exit 1
fi
